// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGDS.Infrastructure.Data;

#nullable disable

namespace SGDS.Infrastructure.Migrations
{
    [DbContext(typeof(SgdsDbContext))]
    [Migration("20260821140910_CrearModuloPasivosLaborales")]
    partial class CrearModuloPasivosLaborales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGDS.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("DireccionIp")
                        .HasColumnType("text")
                        .HasColumnName("direccion_ip");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Modulo")
                        .HasColumnType("text")
                        .HasColumnName("modulo");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_auditoria_proyecto_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditoria_usuario_id");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Ciudadano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id")
                        .HasName("pk_ciudadanos");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("ix_ciudadanos_numero_documento");

                    b.ToTable("ciudadanos", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta_archivo");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoArchivo")
                        .HasColumnType("text")
                        .HasColumnName("tipo_archivo");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_documentos_solicitud_id");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Correo")
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("RepresentanteLegal")
                        .HasColumnType("text")
                        .HasColumnName("representante_legal");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_nit");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.EstampillaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEstampillas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_estampillas");

                    b.Property<string>("CategoriaProducto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria_producto");

                    b.Property<int>("CodigoFinal")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_final");

                    b.Property<int>("CodigoInicial")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_inicial");

                    b.Property<int?>("ContenidoNetoCc")
                        .HasColumnType("integer")
                        .HasColumnName("contenido_neto_cc");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal?>("GradoAlcoholimetrico")
                        .HasColumnType("numeric")
                        .HasColumnName("grado_alcoholimetrico");

                    b.Property<string>("LoteProduccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lote_produccion");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_anulacion");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_producto");

                    b.Property<string>("NumeroDeclaracionImportacion")
                        .HasColumnType("text")
                        .HasColumnName("numero_declaracion_importacion");

                    b.Property<string>("NumeroTornaguia")
                        .HasColumnType("text")
                        .HasColumnName("numero_tornaguia");

                    b.Property<string>("OrigenProducto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen_producto");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefijo");

                    b.Property<string>("RegistroIntroduccion")
                        .HasColumnType("text")
                        .HasColumnName("registro_introduccion");

                    b.Property<string>("RegistroInvima")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registro_invima");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<int>("SolicitudInfoconsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_infoconsumo_id");

                    b.Property<int?>("UnidadesPorCajetilla")
                        .HasColumnType("integer")
                        .HasColumnName("unidades_por_cajetilla");

                    b.HasKey("Id")
                        .HasName("pk_estampillas_fisicas");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasDatabaseName("ix_estampillas_fisicas_solicitud_id");

                    b.HasIndex("SolicitudInfoconsumoId")
                        .HasDatabaseName("ix_estampillas_fisicas_solicitud_infoconsumo_id");

                    b.ToTable("estampillas_fisicas", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_historial_estados");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_historial_estados_solicitud_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historial_estados_usuario_id");

                    b.ToTable("historial_estados", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.InstrumentoPasivoLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Instrumento")
                        .HasColumnType("text")
                        .HasColumnName("instrumento");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("RegimenPensional")
                        .HasColumnType("text")
                        .HasColumnName("regimen_pensional");

                    b.Property<string>("ServidorDocumento")
                        .HasColumnType("text")
                        .HasColumnName("servidor_documento");

                    b.Property<string>("ServidorNombre")
                        .HasColumnType("text")
                        .HasColumnName("servidor_nombre");

                    b.Property<int?>("SolicitudColpensionesId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_colpensiones_id");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<int?>("TiempoLaboradoMeses")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_laborado_meses");

                    b.Property<int?>("TiempoTotalAportesMeses")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_total_aportes_meses");

                    b.Property<decimal?>("ValorMesadaPensional")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_mesada_pensional");

                    b.HasKey("Id")
                        .HasName("pk_instrumentos_pasivo_laboral");

                    b.HasIndex("SolicitudColpensionesId")
                        .HasDatabaseName("ix_instrumentos_pasivo_laboral_solicitud_colpensiones_id");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasDatabaseName("ix_instrumentos_pasivo_laboral_solicitud_id");

                    b.ToTable("instrumentos_pasivo_laboral", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.LoteGoTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadUids")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_uids");

                    b.Property<DateTime>("FechaProduccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_produccion");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_lote");

                    b.Property<string>("PrefijoUid")
                        .HasColumnType("text")
                        .HasColumnName("prefijo_uid");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("producto");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<int?>("UidFinal")
                        .HasColumnType("integer")
                        .HasColumnName("uid_final");

                    b.Property<int?>("UidInicial")
                        .HasColumnType("integer")
                        .HasColumnName("uid_inicial");

                    b.Property<int>("UnidadesLote")
                        .HasColumnType("integer")
                        .HasColumnName("unidades_lote");

                    b.HasKey("Id")
                        .HasName("pk_lotes_gotrace");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasDatabaseName("ix_lotes_gotrace_solicitud_id");

                    b.ToTable("lotes_gotrace", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("EstadoPersonalizado")
                        .HasColumnType("text")
                        .HasColumnName("estado_personalizado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_proyectos");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_proyectos_codigo");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.PuntoControlGoTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmado");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_confirmacion");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("habilitado");

                    b.Property<int>("LoteGoTraceId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_go_trace_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_puntos_control_gotrace");

                    b.HasIndex("LoteGoTraceId")
                        .HasDatabaseName("ix_puntos_control_gotrace_lote_go_trace_id");

                    b.ToTable("puntos_control_gotrace", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formato");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta_archivo");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("integer")
                        .HasColumnName("total_registros");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_reportes");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_reportes_proyecto_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_reportes_usuario_id");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiudadanoId")
                        .HasColumnType("integer")
                        .HasColumnName("ciudadano_id");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_adicionales");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_limite");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<int?>("TipoSolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_solicitud_id");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_asignado_id");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_solicitudes");

                    b.HasIndex("CiudadanoId")
                        .HasDatabaseName("ix_solicitudes_ciudadano_id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_solicitudes_empresa_id");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_solicitudes_proyecto_id");

                    b.HasIndex("TipoSolicitudId")
                        .HasDatabaseName("ix_solicitudes_tipo_solicitud_id");

                    b.HasIndex("UsuarioAsignadoId")
                        .HasDatabaseName("ix_solicitudes_usuario_asignado_id");

                    b.HasIndex("VehiculoId")
                        .HasDatabaseName("ix_solicitudes_vehiculo_id");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.SolicitudAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento_identidad");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("RolSolicitado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol_solicitado");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_solicitud_acceso");

                    b.ToTable("solicitud_acceso", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.SolicitudAccesoProyecto", b =>
                {
                    b.Property<int>("SolicitudAccesoId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_acceso_id");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.HasKey("SolicitudAccesoId", "ProyectoId")
                        .HasName("pk_solicitud_acceso_proyecto");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_solicitud_acceso_proyecto_proyecto_id");

                    b.ToTable("solicitud_acceso_proyecto", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.HasKey("Id")
                        .HasName("pk_tipos_solicitud");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_tipos_solicitud_proyecto_id");

                    b.ToTable("tipos_solicitud", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Nombre = "Contrato",
                            ProyectoId = 10
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Nombre = "Convenio",
                            ProyectoId = 10
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Nombre = "Acto sin cuantía",
                            ProyectoId = 10
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Nombre = "Movilización",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Nombre = "Reenvío",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Nombre = "Tránsito",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Nombre = "Tránsito local",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Nombre = "Tránsito declarado",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            Nombre = "Expedición de estampilla",
                            ProyectoId = 7
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            Nombre = "Registro de trazabilidad de lote",
                            ProyectoId = 9
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            Nombre = "Gestión de pasivo pensional",
                            ProyectoId = 6
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            Nombre = "Gestión de pasivo laboral",
                            ProyectoId = 6
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            Nombre = "Consulta de expediente digital",
                            ProyectoId = 6
                        });
                });

            modelBuilder.Entity("SGDS.Domain.Entities.TornaguiaInfoconsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaProducto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria_producto");

                    b.Property<string>("CedulaConductor")
                        .HasColumnType("text")
                        .HasColumnName("cedula_conductor");

                    b.Property<string>("Conductor")
                        .HasColumnType("text")
                        .HasColumnName("conductor");

                    b.Property<string>("DepartamentoDestino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento_destino");

                    b.Property<string>("DepartamentoOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento_origen");

                    b.Property<string>("EmpresaTransportadora")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("empresa_transportadora");

                    b.Property<DateTime?>("FechaExpedicion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expedicion");

                    b.Property<DateTime?>("FechaLegalizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_legalizacion");

                    b.Property<DateTime?>("FechaPagoConfirmado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago_confirmado");

                    b.Property<DateTime?>("FechaVigenciaLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vigencia_limite");

                    b.Property<decimal?>("GradosAlcoholimetricos")
                        .HasColumnType("numeric")
                        .HasColumnName("grados_alcoholimetricos");

                    b.Property<int?>("LoteGoTraceSolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_go_trace_solicitud_id");

                    b.Property<string>("MunicipioDestino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("municipio_destino");

                    b.Property<string>("MunicipioOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("municipio_origen");

                    b.Property<string>("NitTransportador")
                        .HasColumnType("text")
                        .HasColumnName("nit_transportador");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<bool>("PagoConfirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("pago_confirmado");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placa_vehiculo");

                    b.Property<decimal>("PvpCertificado")
                        .HasColumnType("numeric")
                        .HasColumnName("pvp_certificado");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("TipoTransporte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_transporte");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("text")
                        .HasColumnName("tipo_vehiculo");

                    b.Property<int>("UnidadesFisicas")
                        .HasColumnType("integer")
                        .HasColumnName("unidades_fisicas");

                    b.HasKey("Id")
                        .HasName("pk_tornaguias_infoconsumo");

                    b.HasIndex("LoteGoTraceSolicitudId")
                        .HasDatabaseName("ix_tornaguias_infoconsumo_lote_go_trace_solicitud_id");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasDatabaseName("ix_tornaguias_infoconsumo_solicitud_id");

                    b.HasIndex("PlacaVehiculo", "NitTransportador")
                        .HasDatabaseName("ix_tornaguias_infoconsumo_placa_vehiculo_nit_transportador");

                    b.ToTable("tornaguias_infoconsumo", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.UsuarioProyecto", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "ProyectoId")
                        .HasName("pk_usuario_proyecto");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_usuario_proyecto_proyecto_id");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_proyecto_rol_id");

                    b.ToTable("usuario_proyecto", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiudadanoId")
                        .HasColumnType("integer")
                        .HasColumnName("ciudadano_id");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<int?>("Modelo")
                        .HasColumnType("integer")
                        .HasColumnName("modelo");

                    b.Property<string>("NumeroChasis")
                        .HasColumnType("text")
                        .HasColumnName("numero_chasis");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placa");

                    b.HasKey("Id")
                        .HasName("pk_vehiculos");

                    b.HasIndex("CiudadanoId")
                        .HasDatabaseName("ix_vehiculos_ciudadano_id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_vehiculos_empresa_id");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ix_vehiculos_placa");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .HasConstraintName("fk_auditoria_proyectos_proyecto_id");

                    b.HasOne("SGDS.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_auditoria_usuarios_usuario_id");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Documento", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Documentos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_solicitudes_solicitud_id");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.EstampillaFisica", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Solicitud", "Solicitud")
                        .WithOne("EstampillaFisica")
                        .HasForeignKey("SGDS.Domain.Entities.EstampillaFisica", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estampillas_fisicas_solicitudes_solicitud_id");

                    b.HasOne("SGDS.Domain.Entities.Solicitud", "SolicitudInfoconsumo")
                        .WithMany()
                        .HasForeignKey("SolicitudInfoconsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estampillas_fisicas_solicitudes_solicitud_infoconsumo_id");

                    b.Navigation("Solicitud");

                    b.Navigation("SolicitudInfoconsumo");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historial_estados_solicitudes_solicitud_id");

                    b.HasOne("SGDS.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_historial_estados_usuarios_usuario_id");

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.InstrumentoPasivoLaboral", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Solicitud", "SolicitudColpensiones")
                        .WithMany()
                        .HasForeignKey("SolicitudColpensionesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instrumentos_pasivo_laboral_solicitudes_solicitud_colpensio");

                    b.HasOne("SGDS.Domain.Entities.Solicitud", "Solicitud")
                        .WithOne("InstrumentoPasivoLaboral")
                        .HasForeignKey("SGDS.Domain.Entities.InstrumentoPasivoLaboral", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instrumentos_pasivo_laboral_solicitudes_solicitud_id");

                    b.Navigation("Solicitud");

                    b.Navigation("SolicitudColpensiones");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.LoteGoTrace", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Solicitud", "Solicitud")
                        .WithOne("LoteGoTrace")
                        .HasForeignKey("SGDS.Domain.Entities.LoteGoTrace", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_gotrace_solicitudes_solicitud_id");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.PuntoControlGoTrace", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.LoteGoTrace", "LoteGoTrace")
                        .WithMany("PuntosControl")
                        .HasForeignKey("LoteGoTraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_puntos_control_gotrace_lotes_gotrace_lote_go_trace_id");

                    b.Navigation("LoteGoTrace");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .HasConstraintName("fk_reportes_proyectos_proyecto_id");

                    b.HasOne("SGDS.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_reportes_usuarios_usuario_id");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Ciudadano", "Ciudadano")
                        .WithMany("Solicitudes")
                        .HasForeignKey("CiudadanoId")
                        .HasConstraintName("fk_solicitudes_ciudadanos_ciudadano_id");

                    b.HasOne("SGDS.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Solicitudes")
                        .HasForeignKey("EmpresaId")
                        .HasConstraintName("fk_solicitudes_empresas_empresa_id");

                    b.HasOne("SGDS.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Solicitudes")
                        .HasForeignKey("ProyectoId")
                        .HasConstraintName("fk_solicitudes_proyectos_proyecto_id");

                    b.HasOne("SGDS.Domain.Entities.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .HasConstraintName("fk_solicitudes_tipos_solicitudes_tipo_solicitud_id");

                    b.HasOne("SGDS.Domain.Entities.Usuario", "UsuarioAsignado")
                        .WithMany("SolicitudesAsignadas")
                        .HasForeignKey("UsuarioAsignadoId")
                        .HasConstraintName("fk_solicitudes_usuarios_usuario_asignado_id");

                    b.HasOne("SGDS.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Solicitudes")
                        .HasForeignKey("VehiculoId")
                        .HasConstraintName("fk_solicitudes_vehiculos_vehiculo_id");

                    b.Navigation("Ciudadano");

                    b.Navigation("Empresa");

                    b.Navigation("Proyecto");

                    b.Navigation("TipoSolicitud");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.SolicitudAccesoProyecto", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("SolicitudesAcceso")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitud_acceso_proyecto_proyectos_proyecto_id");

                    b.HasOne("SGDS.Domain.Entities.SolicitudAcceso", "SolicitudAcceso")
                        .WithMany("ProyectosSolicitados")
                        .HasForeignKey("SolicitudAccesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitud_acceso_proyecto_solicitud_acceso_solicitud_acceso");

                    b.Navigation("Proyecto");

                    b.Navigation("SolicitudAcceso");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.TipoSolicitud", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("TiposSolicitud")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tipos_solicitud_proyectos_proyecto_id");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.TornaguiaInfoconsumo", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Solicitud", "LoteGoTraceSolicitud")
                        .WithMany()
                        .HasForeignKey("LoteGoTraceSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tornaguias_infoconsumo_solicitudes_lote_go_trace_solicitud_");

                    b.HasOne("SGDS.Domain.Entities.Solicitud", "Solicitud")
                        .WithOne("TornaguiaInfoconsumo")
                        .HasForeignKey("SGDS.Domain.Entities.TornaguiaInfoconsumo", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tornaguias_infoconsumo_solicitudes_solicitud_id");

                    b.Navigation("LoteGoTraceSolicitud");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.UsuarioProyecto", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("UsuarioProyectos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_proyecto_proyectos_proyecto_id");

                    b.HasOne("SGDS.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioProyectos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_proyecto_roles_rol_id");

                    b.HasOne("SGDS.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioProyectos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_proyecto_usuarios_usuario_id");

                    b.Navigation("Proyecto");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("SGDS.Domain.Entities.Ciudadano", "Ciudadano")
                        .WithMany("Vehiculos")
                        .HasForeignKey("CiudadanoId")
                        .HasConstraintName("fk_vehiculos_ciudadanos_ciudadano_id");

                    b.HasOne("SGDS.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Vehiculos")
                        .HasForeignKey("EmpresaId")
                        .HasConstraintName("fk_vehiculos_empresas_empresa_id");

                    b.Navigation("Ciudadano");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Ciudadano", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.LoteGoTrace", b =>
                {
                    b.Navigation("PuntosControl");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Proyecto", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("SolicitudesAcceso");

                    b.Navigation("TiposSolicitud");

                    b.Navigation("UsuarioProyectos");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioProyectos");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("EstampillaFisica");

                    b.Navigation("HistorialEstados");

                    b.Navigation("InstrumentoPasivoLaboral");

                    b.Navigation("LoteGoTrace");

                    b.Navigation("TornaguiaInfoconsumo");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.SolicitudAcceso", b =>
                {
                    b.Navigation("ProyectosSolicitados");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("SolicitudesAsignadas");

                    b.Navigation("UsuarioProyectos");
                });

            modelBuilder.Entity("SGDS.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
